### ISSUE TITLE
Improve withdrawal monitoring for chains with infrequent withdrawal

### ISSUE THREAD

**Issue by zchn** [ethereum-optimism/monitorism#70]
We have a heartbeat alert in wd-mon to ensure that the monitoring system is always live and working. The alert logic is to alert whenever there is no withdrawal detected by wd-mon for the past X hour. However, this becomes noisy for chains where withdrawals are infrequent.

We need to ensure that if there is a faulty withdrawal, we will detect it before the withdrawal becomes finalized (3.5 days), so we need to ensure there is at least one heartbeat within the last 3.5 days or shorter. If a chain naturally does not have a withdrawal within the last 3.5 days, the alert becomes noisy.

One solution that also bring additional side benefit is to run a deposit-then-withdrawal prober for the chain. Pseudo code for doing it across all chains in the Superchain:

```
l1_txs = []
for chain_id in Superchain:
   l2_tx = makeL2WithdrawalInitiationTx(chain_id)
   l1_txs.append(makeL1DepositTx(l2_tx))
l1_rpc.execute(l1_txs)
```

**Comment by Ethnical** [comment]
Thanks for the all the work done here! We will continue to track for sure this issue for issue and maybe we should find a way in the future to make this automatically deployed with automation monitoring security project.
To ensure, everywhere new chains (with high frequency withdrawal won't make this again).

**Comment by mds1** [comment]
Deployed on Mainnet here: https://etherscan.io/address/0x90976F9c60d36a8A67baE55A4961d1F778Fb49cE

Transaction for zora here: https://etherscan.io/tx/0xec2c27864cc2cf1708f332f2eadca99ca9b60a08b8b97c52a444322008fec006

**Comment by Ethnical** [comment]
Decided to downgrade the severity to avoid oncall to do that for now
![Image](https://github.com/user-attachments/assets/268e2f1a-bd65-45f1-b046-c071ef1f1a3a)

A possible alternative would be to have an hybrid version as mentionned here
